### ISSUE TITLE
[REQUEST] 1.19

### ISSUE THREAD

**Issue by AlwaysDan007** [Gaming32/fabric-get-current-song#1]
Please update mod to 1.19

**Comment by Gaming32** [comment]
Oop, sorry. Didn't realize anybody actually used my mod.

**Comment by AlwaysDan007** [comment]
Oh wow, well I love this mod! I can't find any other like this.
1.19 would be nice ;)

**Comment by AlwaysDan007** [comment]
i looked in actions, and thanks for providing 1.19

**Comment by Gaming32** [comment]
Oh I wasn't sure the one in Actions worked, that's why I didn't publish it.

**Comment by AlwaysDan007** [comment]
ok ok, but thanks
